export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  SUBMIT = 'submit',
  REVIEW = 'review',
  REVIEW_APPROVE = 'review_approve',
  REVIEW_REJECT = 'review_reject',
  VERIFY = 'verify',
  VERIFY_APPROVE = 'verify_approve',
  VERIFY_REJECT = 'verify_reject',
  ARCHIVE = 'archive',
  CORRECT = 'correct',
  TIMEOUT_HANDLE = 'timeout_handle',
  UPDATE_STATUS = 'update_status',
  DELETE = 'delete',
  WEEKLY_REPORT_CREATE = 'weekly_report_create',
  WEEKLY_REPORT_UPDATE = 'weekly_report_update',
  DEVIATION_CREATE = 'deviation_create',
  DEVIATION_UPDATE = 'deviation_update',
  DEVIATION_APPROVE = 'deviation_approve',
  OWNER_REPORT_CREATE = 'owner_report_create',
  OWNER_REPORT_UPDATE = 'owner_report_update',
  OWNER_REPORT_ACKNOWLEDGE = 'owner_report_acknowledge',
  BATCH_PROCESS = 'batch_process',
}

export const OperationTypeLabel: Record<OperationType, string> = {
  [OperationType.CREATE]: '创建',
  [OperationType.UPDATE]: '更新',
  [OperationType.SUBMIT]: '提交',
  [OperationType.REVIEW]: '审核',
  [OperationType.REVIEW_APPROVE]: '审核通过',
  [OperationType.REVIEW_REJECT]: '审核驳回',
  [OperationType.VERIFY]: '复核',
  [OperationType.VERIFY_APPROVE]: '复核通过',
  [OperationType.VERIFY_REJECT]: '复核驳回',
  [OperationType.ARCHIVE]: '归档',
  [OperationType.CORRECT]: '补正',
  [OperationType.TIMEOUT_HANDLE]: '超时处理',
  [OperationType.UPDATE_STATUS]: '状态更新',
  [OperationType.DELETE]: '删除',
  [OperationType.WEEKLY_REPORT_CREATE]: '新增周报',
  [OperationType.WEEKLY_REPORT_UPDATE]: '更新周报',
  [OperationType.DEVIATION_CREATE]: '新增偏差分析',
  [OperationType.DEVIATION_UPDATE]: '更新偏差分析',
  [OperationType.DEVIATION_APPROVE]: '偏差分析审批',
  [OperationType.OWNER_REPORT_CREATE]: '新增业主汇报',
  [OperationType.OWNER_REPORT_UPDATE]: '更新业主汇报',
  [OperationType.OWNER_REPORT_ACKNOWLEDGE]: '业主汇报确认',
  [OperationType.BATCH_PROCESS]: '批量办理',
};
