# Generated by Django 4.2.11 on 2026-06-11 05:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('registrar', '物料变更登记员'), ('supervisor', '物料变更审核主管'), ('reviewer', '电子元器件工厂复核负责人')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('material_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=200)),
                ('change_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核主管办理'), ('supplement_required', '需补正附件'), ('pending_final', '待复核归档'), ('returned', '已退回'), ('archived', '已归档'), ('overdue', '已超时')], default='draft', max_length=30)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('audit_remark', models.TextField(blank=True, null=True)),
                ('supplement_note', models.TextField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_orders', to='api.user')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_orders', to='api.user')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_orders', to='api.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建'), ('submitted', '提交审核'), ('approved_supervisor', '审核主管通过'), ('rejected_supervisor', '审核主管退回'), ('supplemented', '补正附件'), ('approved_final', '复核通过归档'), ('rejected_final', '复核退回'), ('attachment_rejected', '附件驳回'), ('attachment_approved', '附件通过'), ('remark_added', '添加审计备注'), ('marked_overdue', '标记超时')], max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.materialchangeorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('rejected', '已驳回'), ('approved', '已通过')], default='uploaded', max_length=20)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.materialchangeorder')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_attachments', to='api.user')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
    ]
