# Generated by Django 4.2.30 on 2026-06-20 22:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "real_name",
                    models.CharField(blank=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("registrar", "订舱登记员"),
                            ("supervisor", "订舱审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        default="registrar",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="手机号"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BookingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="订舱单号"
                    ),
                ),
                ("batch_no", models.CharField(max_length=50, verbose_name="批次号")),
                ("customer", models.CharField(max_length=100, verbose_name="客户名称")),
                (
                    "forwarder",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="货代/船公司"
                    ),
                ),
                (
                    "port_of_loading",
                    models.CharField(blank=True, max_length=50, verbose_name="起运港"),
                ),
                (
                    "port_of_discharge",
                    models.CharField(blank=True, max_length=50, verbose_name="目的港"),
                ),
                (
                    "container_type",
                    models.CharField(blank=True, max_length=30, verbose_name="柜型"),
                ),
                ("container_qty", models.IntegerField(default=1, verbose_name="柜量")),
                ("cargo_desc", models.TextField(blank=True, verbose_name="货物描述")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="重量(吨)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="体积(立方)",
                    ),
                ),
                (
                    "etd",
                    models.DateField(blank=True, null=True, verbose_name="预计开船日"),
                ),
                (
                    "eta",
                    models.DateField(blank=True, null=True, verbose_name="预计到港日"),
                ),
                (
                    "bl_no",
                    models.CharField(blank=True, max_length=50, verbose_name="提单号"),
                ),
                (
                    "vessel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="船名航次"
                    ),
                ),
                (
                    "so_no",
                    models.CharField(blank=True, max_length=50, verbose_name="SO号"),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending_review", "待审核"),
                            ("review_passed", "审核通过"),
                            ("booked", "已订舱"),
                            ("booking_failed", "订舱失败"),
                            ("returned", "已退回"),
                            ("correcting", "补正中"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="订舱状态",
                    ),
                ),
                (
                    "loading_status",
                    models.CharField(
                        choices=[
                            ("not_arranged", "未安排"),
                            ("pending_confirm", "待确认"),
                            ("confirmed", "已确认"),
                            ("loaded", "已装柜"),
                            ("load_failed", "装柜失败"),
                        ],
                        default="not_arranged",
                        max_length=20,
                        verbose_name="装柜状态",
                    ),
                ),
                (
                    "bl_status",
                    models.CharField(
                        choices=[
                            ("not_issued", "未出单"),
                            ("pending_collect", "待回收"),
                            ("collected", "已回收"),
                            ("archived", "已归档"),
                        ],
                        default="not_issued",
                        max_length=20,
                        verbose_name="提单状态",
                    ),
                ),
                (
                    "is_exception",
                    models.BooleanField(default=False, verbose_name="是否异常"),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("none", "无"),
                            ("missing_materials", "缺材料"),
                            ("timeout", "超时"),
                            ("rejected", "退回"),
                            ("status_mismatch", "状态不一致"),
                            ("duplicate_batch", "重复批次"),
                        ],
                        default="none",
                        max_length=30,
                        verbose_name="异常类型",
                    ),
                ),
                (
                    "exception_note",
                    models.TextField(blank=True, verbose_name="异常说明"),
                ),
                (
                    "return_reason",
                    models.TextField(blank=True, verbose_name="退回原因"),
                ),
                ("audit_remark", models.TextField(blank=True, verbose_name="审计备注")),
                (
                    "result_note",
                    models.TextField(blank=True, verbose_name="处理结果说明"),
                ),
                (
                    "offline_booking_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "草稿"),
                            ("pending_review", "待审核"),
                            ("review_passed", "审核通过"),
                            ("booked", "已订舱"),
                            ("booking_failed", "订舱失败"),
                            ("returned", "已退回"),
                            ("correcting", "补正中"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="离线台账-订舱状态",
                    ),
                ),
                (
                    "offline_loading_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_arranged", "未安排"),
                            ("pending_confirm", "待确认"),
                            ("confirmed", "已确认"),
                            ("loaded", "已装柜"),
                            ("load_failed", "装柜失败"),
                        ],
                        default="not_arranged",
                        max_length=20,
                        verbose_name="离线台账-装柜状态",
                    ),
                ),
                (
                    "offline_bl_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_issued", "未出单"),
                            ("pending_collect", "待回收"),
                            ("collected", "已回收"),
                            ("archived", "已归档"),
                        ],
                        default="not_issued",
                        max_length=20,
                        verbose_name="离线台账-提单状态",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="办理时限"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归档时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "archivist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="归档人",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
            ],
            options={
                "verbose_name": "订舱申请",
                "verbose_name_plural": "订舱申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "发起申请"),
                            ("submit", "提交审核"),
                            ("review_pass", "审核通过"),
                            ("review_reject", "审核退回"),
                            ("book_confirm", "订舱确认"),
                            ("book_fail", "订舱失败"),
                            ("correct", "补正资料"),
                            ("resubmit", "重新提交"),
                            ("load_arrange", "安排装柜"),
                            ("load_confirm", "装柜确认"),
                            ("load_fail", "装柜失败"),
                            ("bl_issue", "提单出单"),
                            ("bl_collect", "提单回收"),
                            ("review_archive", "复核归档"),
                            ("offline_fill", "离线台账回填"),
                            ("audit_note", "添加审计备注"),
                            ("upload_attach", "上传附件"),
                            ("batch_result", "批量处理"),
                        ],
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="操作人姓名"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("registrar", "订舱登记员"),
                            ("supervisor", "订舱审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        max_length=20,
                        verbose_name="操作人角色",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="变更前状态"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="变更后状态"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注/原因")),
                (
                    "field_changed",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="变更字段"
                    ),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="旧值")),
                ("new_value", models.TextField(blank=True, verbose_name="新值")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to="booking.bookingapplication",
                        verbose_name="订舱申请",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作记录",
                "verbose_name_plural": "操作记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineLedgerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="回填字段"),
                ),
                (
                    "field_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="字段说明"
                    ),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="原值")),
                ("new_value", models.TextField(blank=True, verbose_name="新值")),
                (
                    "source",
                    models.CharField(
                        default="离线台账Excel", max_length=50, verbose_name="数据来源"
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="操作人姓名"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="回填时间"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_records",
                        to="booking.bookingapplication",
                        verbose_name="订舱申请",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_ops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "离线台账回填记录",
                "verbose_name_plural": "离线台账回填记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("booking", "订舱审核"),
                            ("loading", "装柜审核"),
                            ("bl", "提单审核"),
                            ("final", "复核归档"),
                        ],
                        max_length=20,
                        verbose_name="审计类型",
                    ),
                ),
                (
                    "auditor_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="审计人姓名"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "通过"),
                            ("fail", "失败"),
                            ("return", "退回"),
                        ],
                        max_length=10,
                        verbose_name="审计结果",
                    ),
                ),
                (
                    "fail_reason",
                    models.TextField(blank=True, verbose_name="失败/退回原因"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="审计时间"),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审计人",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="booking.bookingapplication",
                        verbose_name="订舱申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking_doc", "订舱资料"),
                            ("loading_doc", "装柜单据"),
                            ("bl_doc", "提单文件"),
                            ("certificate", "证明文件"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="文件分类",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/", verbose_name="文件"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, max_length=255, verbose_name="文件名"),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="booking.bookingapplication",
                        verbose_name="订舱申请",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "附件",
                "verbose_name_plural": "附件",
                "ordering": ["-created_at"],
            },
        ),
    ]
