// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $selections_id_ from "./routes/selections/[id].tsx";
import * as $App from "./islands/App.tsx";
import * as $SelectionDetail from "./islands/SelectionDetail.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/selections/[id].tsx": $selections_id_,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/SelectionDetail.tsx": $SelectionDetail,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
