// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $audit from "./routes/audit.tsx";
import * as $batch from "./routes/batch.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $transfer_id_ from "./routes/transfer/[id].tsx";
import * as $AuditLogList from "./islands/AuditLogList.tsx";
import * as $BatchList from "./islands/BatchList.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $TransferDashboard from "./islands/TransferDashboard.tsx";
import * as $TransferDetail from "./islands/TransferDetail.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/audit.tsx": $audit,
    "./routes/batch.tsx": $batch,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/transfer/[id].tsx": $transfer_id_,
  },
  islands: {
    "./islands/AuditLogList.tsx": $AuditLogList,
    "./islands/BatchList.tsx": $BatchList,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/TransferDashboard.tsx": $TransferDashboard,
    "./islands/TransferDetail.tsx": $TransferDetail,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
