import os

BACKEND_PORT = int(os.environ.get("BACKEND_PORT", 8005))
FRONTEND_PORT = int(os.environ.get("FRONTEND_PORT", 3005))
FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", f"http://localhost:{FRONTEND_PORT}")
DATABASE_PATH = os.environ.get("DATABASE_PATH", os.path.join(os.path.dirname(__file__), "transfer.db"))

ROLES = ["登记员", "审核主管", "复核负责人"]

STATUS_DRAFT = "草稿"
STATUS_PENDING_REVIEW = "待审核"
STATUS_PENDING_CORRECTION = "待补正"
STATUS_UNDER_REVIEW = "审核中"
STATUS_PENDING_ARCHIVAL = "待复核归档"
STATUS_UNDER_ARCHIVAL = "复核归档中"
STATUS_COMPLETED = "已办结"
STATUS_OVERDUE = "已逾期"
STATUS_REJECTED = "已驳回"

ALL_STATUSES = [
    STATUS_DRAFT, STATUS_PENDING_REVIEW, STATUS_PENDING_CORRECTION,
    STATUS_UNDER_REVIEW, STATUS_PENDING_ARCHIVAL, STATUS_UNDER_ARCHIVAL,
    STATUS_COMPLETED, STATUS_OVERDUE, STATUS_REJECTED
]

QUEUE_MAP = {
    "登记员": [STATUS_DRAFT, STATUS_PENDING_REVIEW, STATUS_PENDING_CORRECTION, STATUS_OVERDUE],
    "审核主管": [STATUS_PENDING_REVIEW, STATUS_UNDER_REVIEW, STATUS_REJECTED],
    "复核负责人": [STATUS_PENDING_ARCHIVAL, STATUS_UNDER_ARCHIVAL],
}

ACTIONS = {
    "登记员": ["发起申请", "提交审核", "补正提交"],
    "审核主管": ["开始审核", "审核通过", "审核驳回", "要求补正"],
    "复核负责人": ["开始复核", "复核归档", "复核退回"],
}

ROLE_ACTION_STATUS = {
    ("登记员", "发起申请"): STATUS_DRAFT,
    ("登记员", "提交审核"): STATUS_PENDING_REVIEW,
    ("登记员", "补正提交"): STATUS_PENDING_REVIEW,
    ("审核主管", "开始审核"): STATUS_UNDER_REVIEW,
    ("审核主管", "审核通过"): STATUS_PENDING_ARCHIVAL,
    ("审核主管", "审核驳回"): STATUS_REJECTED,
    ("审核主管", "要求补正"): STATUS_PENDING_CORRECTION,
    ("复核负责人", "开始复核"): STATUS_UNDER_ARCHIVAL,
    ("复核负责人", "复核归档"): STATUS_COMPLETED,
    ("复核负责人", "复核退回"): STATUS_PENDING_REVIEW,
}

VALID_TRANSITIONS = {
    STATUS_DRAFT: [STATUS_PENDING_REVIEW],
    STATUS_PENDING_REVIEW: [STATUS_UNDER_REVIEW, STATUS_PENDING_CORRECTION],
    STATUS_PENDING_CORRECTION: [STATUS_PENDING_REVIEW],
    STATUS_UNDER_REVIEW: [STATUS_PENDING_ARCHIVAL, STATUS_REJECTED, STATUS_PENDING_CORRECTION],
    STATUS_PENDING_ARCHIVAL: [STATUS_UNDER_ARCHIVAL],
    STATUS_UNDER_ARCHIVAL: [STATUS_COMPLETED, STATUS_PENDING_REVIEW],
    STATUS_REJECTED: [STATUS_DRAFT],
    STATUS_OVERDUE: [STATUS_PENDING_REVIEW, STATUS_PENDING_CORRECTION, STATUS_REJECTED],
}

REQUIRED_MATERIALS = [
    "机动车登记证书",
    "行驶证",
    "买卖合同",
    "双方身份证明",
    "车辆购置税完税证明",
    "交强险保单",
]

CORRECTION_MATERIALS = [
    "补正说明",
    "补正材料",
]

DEADLINE_HOURS = {
    STATUS_PENDING_REVIEW: 48,
    STATUS_PENDING_CORRECTION: 72,
    STATUS_UNDER_REVIEW: 24,
    STATUS_PENDING_ARCHIVAL: 24,
    STATUS_UNDER_ARCHIVAL: 12,
}
