# Generated by Django 6.0.6 on 2026-06-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchoperationitem',
            name='order_id_tmp',
            field=models.IntegerField(default=0, verbose_name='临时订单ID(用于不存在的订单)'),
        ),
        migrations.AddField(
            model_name='batchoperationitem',
            name='version',
            field=models.IntegerField(default=0, verbose_name='提交时的版本号'),
        ),
        migrations.AlterField(
            model_name='batchoperationitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='trade_order.tradeorder', verbose_name='订单'),
        ),
    ]
