# Generated by Django 6.0.6 on 2026-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_order', '0002_batchoperationitem_order_id_tmp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchoperationitem',
            name='responsible_role',
            field=models.CharField(blank=True, max_length=30, verbose_name='责任岗位'),
        ),
        migrations.AddField(
            model_name='batchoperationitem',
            name='suggestion',
            field=models.TextField(blank=True, verbose_name='处理建议'),
        ),
    ]
