# Generated by Django 6.0.6 on 2026-06-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_order', '0003_batchoperationitem_responsible_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchoperationitem',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
        migrations.AddField(
            model_name='batchoperationitem',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_prev_items', to='trade_order.batchoperationitem', verbose_name='由哪个成功批次解决'),
        ),
        migrations.AddField(
            model_name='batchoperationitem',
            name='resolved_status',
            field=models.CharField(choices=[('unresolved', '未处理'), ('corrected', '已补正'), ('resubmitted', '已重新提交')], default='unresolved', max_length=20, verbose_name='解决状态'),
        ),
    ]
