/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthPaymentVerificationsIndexRouteImport } from './routes/_auth.payment-verifications.index'
import { Route as AuthOperationLogsIndexRouteImport } from './routes/_auth.operation-logs.index'
import { Route as AuthConfirmationOrdersIndexRouteImport } from './routes/_auth.confirmation-orders.index'
import { Route as AuthAccountsReceivableIndexRouteImport } from './routes/_auth.accounts-receivable.index'
import { Route as AuthConfirmationOrdersIdRouteImport } from './routes/_auth.confirmation-orders.$id'
import { Route as AuthAccountsReceivableIdRouteImport } from './routes/_auth.accounts-receivable.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaymentVerificationsIndexRoute =
  AuthPaymentVerificationsIndexRouteImport.update({
    id: '/payment-verifications/',
    path: '/payment-verifications/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOperationLogsIndexRoute = AuthOperationLogsIndexRouteImport.update({
  id: '/operation-logs/',
  path: '/operation-logs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmationOrdersIndexRoute =
  AuthConfirmationOrdersIndexRouteImport.update({
    id: '/confirmation-orders/',
    path: '/confirmation-orders/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAccountsReceivableIndexRoute =
  AuthAccountsReceivableIndexRouteImport.update({
    id: '/accounts-receivable/',
    path: '/accounts-receivable/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConfirmationOrdersIdRoute =
  AuthConfirmationOrdersIdRouteImport.update({
    id: '/confirmation-orders/$id',
    path: '/confirmation-orders/$id',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAccountsReceivableIdRoute =
  AuthAccountsReceivableIdRouteImport.update({
    id: '/accounts-receivable/$id',
    path: '/accounts-receivable/$id',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/accounts-receivable/$id': typeof AuthAccountsReceivableIdRoute
  '/confirmation-orders/$id': typeof AuthConfirmationOrdersIdRoute
  '/accounts-receivable/': typeof AuthAccountsReceivableIndexRoute
  '/confirmation-orders/': typeof AuthConfirmationOrdersIndexRoute
  '/operation-logs/': typeof AuthOperationLogsIndexRoute
  '/payment-verifications/': typeof AuthPaymentVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/accounts-receivable/$id': typeof AuthAccountsReceivableIdRoute
  '/confirmation-orders/$id': typeof AuthConfirmationOrdersIdRoute
  '/accounts-receivable': typeof AuthAccountsReceivableIndexRoute
  '/confirmation-orders': typeof AuthConfirmationOrdersIndexRoute
  '/operation-logs': typeof AuthOperationLogsIndexRoute
  '/payment-verifications': typeof AuthPaymentVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/accounts-receivable/$id': typeof AuthAccountsReceivableIdRoute
  '/_auth/confirmation-orders/$id': typeof AuthConfirmationOrdersIdRoute
  '/_auth/accounts-receivable/': typeof AuthAccountsReceivableIndexRoute
  '/_auth/confirmation-orders/': typeof AuthConfirmationOrdersIndexRoute
  '/_auth/operation-logs/': typeof AuthOperationLogsIndexRoute
  '/_auth/payment-verifications/': typeof AuthPaymentVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/accounts-receivable/$id'
    | '/confirmation-orders/$id'
    | '/accounts-receivable/'
    | '/confirmation-orders/'
    | '/operation-logs/'
    | '/payment-verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/accounts-receivable/$id'
    | '/confirmation-orders/$id'
    | '/accounts-receivable'
    | '/confirmation-orders'
    | '/operation-logs'
    | '/payment-verifications'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/accounts-receivable/$id'
    | '/_auth/confirmation-orders/$id'
    | '/_auth/accounts-receivable/'
    | '/_auth/confirmation-orders/'
    | '/_auth/operation-logs/'
    | '/_auth/payment-verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payment-verifications/': {
      id: '/_auth/payment-verifications/'
      path: '/payment-verifications'
      fullPath: '/payment-verifications/'
      preLoaderRoute: typeof AuthPaymentVerificationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operation-logs/': {
      id: '/_auth/operation-logs/'
      path: '/operation-logs'
      fullPath: '/operation-logs/'
      preLoaderRoute: typeof AuthOperationLogsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirmation-orders/': {
      id: '/_auth/confirmation-orders/'
      path: '/confirmation-orders'
      fullPath: '/confirmation-orders/'
      preLoaderRoute: typeof AuthConfirmationOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts-receivable/': {
      id: '/_auth/accounts-receivable/'
      path: '/accounts-receivable'
      fullPath: '/accounts-receivable/'
      preLoaderRoute: typeof AuthAccountsReceivableIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirmation-orders/$id': {
      id: '/_auth/confirmation-orders/$id'
      path: '/confirmation-orders/$id'
      fullPath: '/confirmation-orders/$id'
      preLoaderRoute: typeof AuthConfirmationOrdersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts-receivable/$id': {
      id: '/_auth/accounts-receivable/$id'
      path: '/accounts-receivable/$id'
      fullPath: '/accounts-receivable/$id'
      preLoaderRoute: typeof AuthAccountsReceivableIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthAccountsReceivableIdRoute: typeof AuthAccountsReceivableIdRoute
  AuthConfirmationOrdersIdRoute: typeof AuthConfirmationOrdersIdRoute
  AuthAccountsReceivableIndexRoute: typeof AuthAccountsReceivableIndexRoute
  AuthConfirmationOrdersIndexRoute: typeof AuthConfirmationOrdersIndexRoute
  AuthOperationLogsIndexRoute: typeof AuthOperationLogsIndexRoute
  AuthPaymentVerificationsIndexRoute: typeof AuthPaymentVerificationsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthAccountsReceivableIdRoute: AuthAccountsReceivableIdRoute,
  AuthConfirmationOrdersIdRoute: AuthConfirmationOrdersIdRoute,
  AuthAccountsReceivableIndexRoute: AuthAccountsReceivableIndexRoute,
  AuthConfirmationOrdersIndexRoute: AuthConfirmationOrdersIndexRoute,
  AuthOperationLogsIndexRoute: AuthOperationLogsIndexRoute,
  AuthPaymentVerificationsIndexRoute: AuthPaymentVerificationsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
