/* eslint-disable */
// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as StatsImport } from './routes/stats'
import { Route as LogsImport } from './routes/logs'
import { Route as IndexImport } from './routes/index'
import { Route as RecordsNewImport } from './routes/records/new'
import { Route as RecordsIdImport } from './routes/records/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const StatsRoute = StatsImport.update({
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const LogsRoute = LogsImport.update({
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecordsNewRoute = RecordsNewImport.update({
  path: '/records/new',
  getParentRoute: () => rootRoute,
} as any)

const RecordsIdRoute = RecordsIdImport.update({
  path: '/records/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      preLoaderRoute: typeof LogsImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
    '/records/$id': {
      preLoaderRoute: typeof RecordsIdImport
      parentRoute: typeof rootRoute
    }
    '/records/new': {
      preLoaderRoute: typeof RecordsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  LogsRoute,
  StatsRoute,
  RecordsIdRoute,
  RecordsNewRoute,
])
