# Generated by Django 6.0.6 on 2026-06-10 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_no', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('lab_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(blank=True, default='', max_length=100)),
                ('experiment_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('student_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交（待实验室审核）'), ('lab_reviewed', '实验室审核通过（待学院确认）'), ('lab_rejected', '实验室退回'), ('confirmed', '学院已确认'), ('college_rejected', '学院退回')], default='draft', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('has_experiment_plan', models.BooleanField(default=False)),
                ('has_material_application', models.BooleanField(default=False)),
                ('has_safety_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('lab_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lab_review_comment', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_comment', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('confirmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to=settings.AUTH_USER_MODEL)),
                ('lab_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_reviews', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('experiment_plan', '实验预约方案'), ('material_application', '耗材申领单'), ('safety_confirmation', '安全确认书')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('is_supplementary', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='reservations.labreservation')),
            ],
            options={
                'db_table': 'evidences',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('submit', '提交'), ('lab_review_pass', '实验室审核通过'), ('lab_reject', '实验室退回'), ('college_confirm', '学院确认'), ('college_reject', '学院退回'), ('supplement', '补录')], max_length=32)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('previous_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reservations.labreservation')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='SupplementaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add_evidence', '补充证据材料'), ('update_info', '更新预约信息'), ('resubmit', '重新提交')], max_length=32)),
                ('description', models.TextField()),
                ('supplementary_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(blank=True, default='', max_length=32)),
                ('related_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.evidence')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_records', to='reservations.labreservation')),
                ('supplementer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplementary_records',
                'ordering': ['-supplementary_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teaching_assistant', '实验助教'), ('lab_admin', '实验室管理员'), ('college_head', '学院负责人')], max_length=32)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
