# Generated by Django 4.2.7 on 2026-06-18 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_no", models.CharField(max_length=32, unique=True)),
                ("action", models.CharField(max_length=50)),
                ("total_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "全部成功"),
                            ("partial_failed", "部分失败"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("remark", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "batch_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_no", models.CharField(max_length=32, unique=True)),
                ("qr_code", models.CharField(max_length=64, unique=True)),
                ("borrower_name", models.CharField(max_length=100)),
                ("borrower_id_card", models.CharField(max_length=18)),
                ("borrower_phone", models.CharField(max_length=20)),
                ("loan_contract_no", models.CharField(max_length=50)),
                (
                    "original_principal",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "original_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("original_due_date", models.DateField()),
                ("extension_days", models.IntegerField()),
                ("extension_reason", models.TextField()),
                ("new_due_date", models.DateField()),
                (
                    "new_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending_review", "待审核"),
                            ("review_approved", "审核通过待复核"),
                            ("returned_for_correction", "退回补正"),
                            ("final_approved", "复核通过待归档"),
                            ("rejected", "已拒绝"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("current_handler_role", models.CharField(blank=True, max_length=50)),
                ("review_opinion", models.TextField(blank=True)),
                ("final_review_opinion", models.TextField(blank=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "final_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "extension_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "sys_role",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="loan.role"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sys_user_profile",
            },
        ),
        migrations.CreateModel(
            name="RepaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_no", models.IntegerField()),
                ("due_date", models.DateField()),
                ("principal", models.DecimalField(decimal_places=2, max_digits=15)),
                ("interest", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_extension_period", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_plans",
                        to="loan.extensionapplication",
                    ),
                ),
            ],
            options={
                "db_table": "repayment_plan",
                "ordering": ["plan_no"],
            },
        ),
        migrations.CreateModel(
            name="QrCodeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_code", models.CharField(max_length=64)),
                (
                    "scan_result",
                    models.CharField(
                        choices=[
                            ("success", "核验通过"),
                            ("invalid", "无效码"),
                            ("duplicate", "重复扫码"),
                            ("wrong_handler", "非当前处理人"),
                            ("wrong_status", "状态不匹配"),
                        ],
                        max_length=30,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_records",
                        to="loan.extensionapplication",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qr_code_record",
                "ordering": ["-scan_time"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("id_card", "身份证"),
                            ("loan_contract", "借款合同"),
                            ("extension_agreement", "展期协议"),
                            ("income_proof", "收入证明"),
                            ("site_photo", "现场照片"),
                            ("other", "其他材料"),
                        ],
                        max_length=30,
                    ),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("file_url", models.CharField(blank=True, max_length=500)),
                ("is_required", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="loan.extensionapplication",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application_material",
                "ordering": ["material_type", "upload_time"],
            },
        ),
        migrations.CreateModel(
            name="BatchTaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("next_step", models.CharField(blank=True, max_length=500)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_items",
                        to="loan.extensionapplication",
                    ),
                ),
                (
                    "batch_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="loan.batchtask",
                    ),
                ),
            ],
            options={
                "db_table": "batch_task_item",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建申请"),
                            ("submit", "提交申请"),
                            ("review", "审核"),
                            ("correct", "补正"),
                            ("final_review", "复核"),
                            ("reject", "拒绝"),
                            ("archive", "归档"),
                            ("scan", "扫码核验"),
                            ("material_upload", "材料上传"),
                            ("material_verify", "材料核验"),
                            ("batch_process", "批量处理"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_detail", models.CharField(blank=True, max_length=200)),
                ("old_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(blank=True, max_length=30)),
                ("remark", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=50)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="loan.extensionapplication",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
