// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/appeals/new": {
    params: {};
  };
  "/appeals/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/appeals/new" | "/appeals/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/appeals.new.tsx": {
    id: "routes/appeals.new";
    page: "/appeals/new";
  };
  "routes/appeals.$id.tsx": {
    id: "routes/appeals.$id";
    page: "/appeals/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/appeals.new": typeof import("./app/routes/appeals.new.tsx");
  "routes/appeals.$id": typeof import("./app/routes/appeals.$id.tsx");
};