# Generated by Django 5.0.4 on 2026-06-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_id_card', models.CharField(max_length=18)),
                ('difficulty_type', models.CharField(choices=[('medical', '医疗'), ('disaster', '灾害'), ('disability', '残疾'), ('low_income', '低收入'), ('other', '其他')], max_length=20)),
                ('difficulty_description', models.TextField()),
                ('assistance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_verify', '待核验'), ('pending_approve', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('opinion_text', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='custom_auth.user')),
            ],
            options={
                'db_table': 'applications_application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('application', '申请阶段'), ('verification', '核验阶段'), ('approval', '审批阶段')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('material_type', models.CharField(blank=True, default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='applications.application')),
            ],
            options={
                'db_table': 'applications_material',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('opinion', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.application')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='custom_auth.user')),
            ],
            options={
                'db_table': 'applications_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('credential_no', models.CharField(blank=True, default='', max_length=50)),
                ('result', models.CharField(choices=[('pass', '通过'), ('invalid_code', '无效编码'), ('duplicate_scan', '重复扫码'), ('role_mismatch', '角色不匹配')], max_length=20)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='applications.application')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='custom_auth.user')),
            ],
            options={
                'db_table': 'applications_scanrecord',
            },
        ),
    ]
