# Generated by Django 5.0.4 on 2026-06-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50)),
                ('application_id', models.IntegerField()),
                ('application_no', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('error', models.TextField()),
                ('suggestion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_failures', to='custom_auth.user')),
            ],
            options={
                'db_table': 'applications_batchfailrecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
