# Generated by Django 5.0.4 on 2026-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_batchfailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfailrecord',
            name='from_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
