# Generated by Django 5.0.4 on 2026-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_batchfailrecord_from_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='overdue_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='deadline_check',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operator_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
