import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATABASE_URL = f"sqlite:///{os.path.join(BASE_DIR, 'follow_up.db')}"

FRONTEND_ORIGIN = "http://localhost:3001"
BACKEND_PORT = 8001

ROLE_TRIAGE_NURSE = "triage_nurse"
ROLE_GP_DOCTOR = "gp_doctor"
ROLE_MEDICAL_DIRECTOR = "medical_director"

STATUS_DRAFT = "draft"
STATUS_PENDING_DOCTOR = "pending_doctor"
STATUS_PENDING_DIRECTOR = "pending_director"
STATUS_CONFIRMED = "confirmed"
STATUS_REJECTED = "rejected"

VALID_TRANSITIONS = {
    STATUS_DRAFT: [STATUS_PENDING_DOCTOR, STATUS_REJECTED],
    STATUS_PENDING_DOCTOR: [STATUS_PENDING_DIRECTOR, STATUS_REJECTED],
    STATUS_PENDING_DIRECTOR: [STATUS_CONFIRMED, STATUS_REJECTED],
    STATUS_CONFIRMED: [],
    STATUS_REJECTED: [],
}

ROLE_PERMISSIONS = {
    ROLE_TRIAGE_NURSE: [STATUS_DRAFT],
    ROLE_GP_DOCTOR: [STATUS_PENDING_DOCTOR],
    ROLE_MEDICAL_DIRECTOR: [STATUS_PENDING_DIRECTOR],
}
