package seed

import (
	"fmt"
	"log"
	"repair-system/internal/models"
	"time"

	"gorm.io/gorm"
)

func InitSeedData(db *gorm.DB) error {
	var userCount int64
	db.Model(&models.User{}).Count(&userCount)
	if userCount > 0 {
		log.Println("用户表已有数据，跳过种子数据初始化")
		return nil
	}

	log.Println("开始初始化种子数据...")

	registrar := &models.User{
		Username:     "registrar",
		RealName:     "张登记",
		Role:         models.RoleRegistrar,
		PasswordHash: "$2a$10$placeholder",
	}
	if err := db.Create(registrar).Error; err != nil {
		return fmt.Errorf("创建登记员失败: %w", err)
	}

	supervisor := &models.User{
		Username:     "supervisor",
		RealName:     "李主管",
		Role:         models.RoleSupervisor,
		PasswordHash: "$2a$10$placeholder",
	}
	if err := db.Create(supervisor).Error; err != nil {
		return fmt.Errorf("创建主管失败: %w", err)
	}

	reviewer := &models.User{
		Username:     "reviewer",
		RealName:     "王复核",
		Role:         models.RoleReviewer,
		PasswordHash: "$2a$10$placeholder",
	}
	if err := db.Create(reviewer).Error; err != nil {
		return fmt.Errorf("创建复核员失败: %w", err)
	}

	log.Printf("创建用户成功: registrar(ID=%d), supervisor(ID=%d), reviewer(ID=%d)",
		registrar.ID, supervisor.ID, reviewer.ID)

	now := time.Now()

	seedOrders := []*models.RepairOrder{
		{
			OrderNo:            generateOrderNo("D", 1),
			CustomerName:       "张三",
			Phone:              "13800138001",
			VehiclePlate:       "京A12345",
			VehicleModel:       "丰田凯美瑞 2023",
			Mileage:            15000,
			AppointmentType:    "常规保养",
			ProblemDescription: "车辆行驶15000公里，需要进行常规保养，包括更换机油、机滤、空滤等。",
			Status:             models.StatusDraft,
			RiskLevel:          models.RiskLow,
			RiskReason:         "",
			Stage:              models.StageAppointment,
			AssignedTechnician: "",
			RepairItems:        "[\"机油更换\",\"机滤更换\",\"空滤更换\",\"全车检查\"]",
			EstimatedCost:      880.0,
			FinalCost:          0,
			EvidenceSubmitted:  false,
			EvidenceList:       "[]",
			Deadline:           now.AddDate(0, 0, 3),
			CurrentHandler:     models.RoleRegistrar,
			Version:            1,
			CreatedByID:        registrar.ID,
			LastOpinion:        "",
			LastResult:         "",
		},
		{
			OrderNo:            generateOrderNo("S", 2),
			CustomerName:       "李四",
			Phone:              "13800138002",
			VehiclePlate:       "京B67890",
			VehicleModel:       "大众帕萨特 2022",
			Mileage:            45000,
			AppointmentType:    "故障维修",
			ProblemDescription: "发动机异响，冷启动时尤为明显，疑似正时链条问题。",
			Status:             models.StatusSubmitted,
			RiskLevel:          models.RiskMedium,
			RiskReason:         "发动机核心部件故障，维修难度较大",
			Stage:              models.StageAppointment,
			AssignedTechnician: "",
			RepairItems:        "[\"发动机诊断\",\"正时链条检查\",\"机油更换\"]",
			EstimatedCost:      3500.0,
			FinalCost:          0,
			EvidenceSubmitted:  true,
			EvidenceList:       "[\"行驶证照片\",\"故障部位照片\",\"维修前检测报告\"]",
			Deadline:           now.AddDate(0, 0, 5),
			CurrentHandler:     models.RoleSupervisor,
			Version:            2,
			CreatedByID:        registrar.ID,
			LastOpinion:        "",
			LastResult:         "提交审核",
		},
		{
			OrderNo:            generateOrderNo("R", 3),
			CustomerName:       "王五",
			Phone:              "13800138003",
			VehiclePlate:       "京C54321",
			VehicleModel:       "奔驰E300L 2021",
			Mileage:            80000,
			AppointmentType:    "事故车",
			ProblemDescription: "车辆发生追尾事故，后保险杠严重受损，后备箱盖变形，尾灯破碎。",
			Status:             models.StatusHighRiskEscalated,
			RiskLevel:          models.RiskHigh,
			RiskReason:         "高端车型事故维修，涉及多个部件更换，可能存在隐藏损伤，维修成本高风险大",
			Stage:              models.StageDispatch,
			AssignedTechnician: "高级技师-陈师傅",
			RepairItems:        "[\"后保险杠更换\",\"后备箱钣金修复\",\"尾灯更换\",\"倒车雷达检测\",\"四轮定位\"]",
			EstimatedCost:      28000.0,
			FinalCost:          0,
			EvidenceSubmitted:  true,
			EvidenceList:       "[\"事故现场照片\",\"车辆损伤照片\",\"保险定损单\",\"行驶证\",\"驾驶证\"]",
			Deadline:           now.AddDate(0, 0, 10),
			CurrentHandler:     models.RoleSupervisor,
			Version:            3,
			CreatedByID:        registrar.ID,
			LastOpinion:        "事故涉及高端车型，维修金额大，风险高，升级处理",
			LastResult:         "风险升级-主管特殊处理",
		},
		{
			OrderNo:            generateOrderNo("A", 4),
			CustomerName:       "赵六",
			Phone:              "13800138004",
			VehiclePlate:       "京D98765",
			VehicleModel:       "本田雅阁 2024",
			Mileage:            5000,
			AppointmentType:    "召回",
			ProblemDescription: "厂家召回通知：燃油泵存在安全隐患，需要免费更换。",
			Status:             models.StatusSupervisorApproved,
			RiskLevel:          models.RiskLow,
			RiskReason:         "",
			Stage:              models.StageDispatch,
			AssignedTechnician: "技师-刘师傅",
			RepairItems:        "[\"燃油泵召回更换\",\"全车安全检查\"]",
			EstimatedCost:      0,
			FinalCost:          0,
			EvidenceSubmitted:  true,
			EvidenceList:       "[\"召回通知书\",\"行驶证照片\",\"车辆VIN码照片\"]",
			Deadline:           now.AddDate(0, 0, 2),
			CurrentHandler:     models.RoleReviewer,
			Version:            3,
			CreatedByID:        registrar.ID,
			LastOpinion:        "厂家召回工单，手续齐全，同意派修",
			LastResult:         "主管审核通过",
		},
		{
			OrderNo:            generateOrderNo("RT", 5),
			CustomerName:       "钱七",
			Phone:              "13800138005",
			VehiclePlate:       "京E11111",
			VehicleModel:       "比亚迪汉EV 2023",
			Mileage:            30000,
			AppointmentType:    "故障维修",
			ProblemDescription: "电池续航异常衰减，充电速度变慢，需要诊断电池系统。",
			Status:             models.StatusReturnedToRegistrar,
			RiskLevel:          models.RiskMedium,
			RiskReason:         "新能源电池系统故障，涉及高压安全",
			Stage:              models.StageAppointment,
			AssignedTechnician: "",
			RepairItems:        "[\"电池系统诊断\",\"BMS软件升级\",\"续航测试\"]",
			EstimatedCost:      5000.0,
			FinalCost:          0,
			EvidenceSubmitted:  false,
			EvidenceList:       "[\"行驶证照片\"]",
			Deadline:           now.AddDate(0, 0, 7),
			CurrentHandler:     models.RoleRegistrar,
			Version:            3,
			CreatedByID:        registrar.ID,
			LastOpinion:        "缺少电池检测报告和高压安全检测证据，请补充完整后重新提交",
			LastResult:         "退回登记员补正",
		},
		{
			OrderNo:            generateOrderNo("AR", 6),
			CustomerName:       "孙八",
			Phone:              "13800138006",
			VehiclePlate:       "京F22222",
			VehicleModel:       "奥迪A6L 2020",
			Mileage:            120000,
			AppointmentType:    "常规保养",
			ProblemDescription: "大保养：更换变速箱油、刹车油、冷却液、火花塞、刹车片等。",
			Status:             models.StatusArchived,
			RiskLevel:          models.RiskLow,
			RiskReason:         "",
			Stage:              models.StageDelivery,
			AssignedTechnician: "技师-周师傅",
			RepairItems:        "[\"变速箱油更换\",\"刹车油更换\",\"冷却液更换\",\"火花塞更换\",\"前后刹车片更换\",\"刹车盘光碟\"]",
			EstimatedCost:      6800.0,
			FinalCost:          7250.0,
			EvidenceSubmitted:  true,
			EvidenceList:       "[\"行驶证\",\"维修前检查单\",\"更换件照片\",\"客户签字确认单\",\"交车照片\"]",
			Deadline:           now.AddDate(0, 0, -1),
			CurrentHandler:     "",
			Version:            5,
			CreatedByID:        registrar.ID,
			LastOpinion:        "全部项目完成，客户确认满意，已交车回访完成",
			LastResult:         "复核通过-归档",
		},
		{
			OrderNo:            generateOrderNo("OV", 7),
			CustomerName:       "周九",
			Phone:              "13800138007",
			VehiclePlate:       "京G33333",
			VehicleModel:       "宝马X5 2022",
			Mileage:            60000,
			AppointmentType:    "故障维修",
			ProblemDescription: "变速箱顿挫严重，3挡升4挡有明显冲击，需要拆解检查变速箱阀体。",
			Status:             models.StatusOverdue,
			RiskLevel:          models.RiskHigh,
			RiskReason:         "变速箱核心故障，维修周期长，配件等待时间不确定，已超出办理时限",
			Stage:              models.StageDispatch,
			AssignedTechnician: "高级技师-吴师傅",
			RepairItems:        "[\"变速箱总成拆卸\",\"阀体检测更换\",\"变速箱油更换\",\"路试匹配\"]",
			EstimatedCost:      38000.0,
			FinalCost:          0,
			EvidenceSubmitted:  true,
			EvidenceList:       "[\"行驶证照片\",\"故障码读取报告\",\"变速箱油样照片\"]",
			Deadline:           now.AddDate(0, 0, -5),
			CurrentHandler:     models.RoleSupervisor,
			Version:            4,
			CreatedByID:        registrar.ID,
			LastOpinion:        "配件德国订货周期2-3周，已超出原定办理时限，标记逾期",
			LastResult:         "状态变更-逾期",
		},
		{
			OrderNo:            generateOrderNo("RJ", 8),
			CustomerName:       "吴十",
			Phone:              "13800138008",
			VehiclePlate:       "京H44444",
			VehicleModel:       "特斯拉Model Y 2024",
			Mileage:            12000,
			AppointmentType:    "事故车",
			ProblemDescription: "右前侧翼子板和车门剐蹭，需要钣金喷漆，Autopilot雷达疑似移位需校准。",
			Status:             models.StatusReviewerRejected,
			RiskLevel:          models.RiskMedium,
			RiskReason:         "智能驾驶雷达校准需要专用设备，数据异常需重做",
			Stage:              models.StageDispatch,
			AssignedTechnician: "技师-郑师傅",
			RepairItems:        "[\"右前翼子板钣金\",\"右前门喷漆\",\"雷达支架校正\",\"Autopilot校准\"]",
			EstimatedCost:      12000.0,
			FinalCost:          0,
			EvidenceSubmitted:  true,
			EvidenceList:       "[\"事故照片\",\"行驶证\",\"定损单\",\"维修前后对比照\"]",
			Deadline:           now.AddDate(0, 0, 4),
			CurrentHandler:     models.RoleSupervisor,
			Version:            5,
			CreatedByID:        registrar.ID,
			LastOpinion:        "Autopilot校准报告数据异常，雷达定位偏差超过标准值2mm，需重新校准后再次提交复核",
			LastResult:         "复核退回-要求重做校准",
		},
	}

	for i, order := range seedOrders {
		if err := db.Create(order).Error; err != nil {
			return fmt.Errorf("创建样例工单 %d 失败: %w", i+1, err)
		}
		log.Printf("创建样例工单: %s - %s (%s)", order.OrderNo, order.CustomerName, order.Status)
	}

	seedOperations := []*models.OrderOperation{
		{
			OrderID:        1,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "客户到店登记，创建保养工单",
			Result:         "创建成功",
			RiskChange:     "none->low",
			EvidenceCheck:  "submitted=false，尚未上传行驶证照片",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Minute * 30),
		},
		{
			OrderID:        2,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "创建工单-发动机异响故障",
			Result:         "创建成功",
			RiskChange:     "none->medium",
			EvidenceCheck:  "submitted=false",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 3),
		},
		{
			OrderID:        2,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "客户已提供全部检测材料，提交主管派修审核",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "证据齐全：行驶证、故障部位照片、检测报告",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 2),
		},
		{
			OrderID:        3,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "事故车登记-奔驰追尾",
			Result:         "创建成功",
			RiskChange:     "none->medium",
			EvidenceCheck:  "submitted=false",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 24),
		},
		{
			OrderID:        3,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "保险定损单已到位，提交审核",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "证据齐全",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 23),
		},
		{
			OrderID:        3,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "supervisor_review_escalate_risk",
			FromStatus:     models.StatusSubmitted,
			ToStatus:       models.StatusHighRiskEscalated,
			Opinion:        "事故涉及奔驰高端车型，维修金额预估超2.8万，后围板可能有隐藏变形需进一步检测，风险升级为高风险，由高级技师专项处理",
			Result:         "风险升级-主管特殊处理",
			RiskChange:     "upgrade:medium->high",
			EvidenceCheck:  "证据齐全，但建议补充底盘探伤照片",
			VersionChecked: 2,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 20),
		},
		{
			OrderID:        4,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "厂家召回工单-燃油泵更换",
			Result:         "创建成功",
			RiskChange:     "none->low",
			EvidenceCheck:  "submitted=false",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 10),
		},
		{
			OrderID:        4,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "召回手续齐全，提交审核",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "召回通知书+VIN码照片验证通过",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 9),
		},
		{
			OrderID:        4,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "supervisor_review_approve",
			FromStatus:     models.StatusSubmitted,
			ToStatus:       models.StatusSupervisorApproved,
			Opinion:        "厂家召回工单，VIN码在召回范围内，手续齐全，分配刘师傅处理，预计工时2小时",
			Result:         "主管审核通过",
			RiskChange:     "none",
			EvidenceCheck:  "材料齐全",
			VersionChecked: 2,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 8),
		},
		{
			OrderID:        5,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "比亚迪汉EV电池续航异常报修",
			Result:         "创建成功",
			RiskChange:     "none->medium",
			EvidenceCheck:  "submitted=false，仅上传行驶证",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 48),
		},
		{
			OrderID:        5,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusDraft,
			Opinion:        "尝试提交工单但证据不全",
			Result:         "失败",
			RiskChange:     "none",
			EvidenceCheck:  "evidence_submitted=false，尚未勾选任何证据项",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 47 - time.Minute*30),
		},
		{
			OrderID:        5,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "补充行驶证照片后提交审核",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "证据齐全：行驶证照片已上传",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 47),
		},
		{
			OrderID:        5,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "supervisor_review_reject",
			FromStatus:     models.StatusSubmitted,
			ToStatus:       models.StatusReturnedToRegistrar,
			Opinion:        "新能源汽车电池系统涉及高压安全，缺少以下必填证据：1)电池健康度检测报告（必须使用原厂诊断设备读取）2)高压系统绝缘检测记录 3)续航测试前后充电百分比截图。请联系客户补充完整后重新提交",
			Result:         "退回登记员补正",
			RiskChange:     "none",
			EvidenceCheck:  "不通过：缺少电池检测报告、高压绝缘记录、续航截图（3项缺失）",
			VersionChecked: 2,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 45),
		},
		{
			OrderID:        3,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "risk_change",
			FromStatus:     models.StatusHighRiskEscalated,
			ToStatus:       models.StatusHighRiskEscalated,
			Opinion:        "尝试降级风险但未提供充分理由",
			Result:         "失败",
			RiskChange:     "high->low",
			EvidenceCheck:  "",
			VersionChecked: 3,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 18),
		},
		{
			OrderID:        7,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "risk_change",
			FromStatus:     models.StatusSupervisorApproved,
			ToStatus:       models.StatusSupervisorApproved,
			Opinion:        "配件延误导致维修周期大幅延长，风险升级为高风险",
			Result:         "成功",
			RiskChange:     "upgrade:medium->high",
			EvidenceCheck:  "",
			VersionChecked: 3,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 15),
		},
		{
			OrderID:        6,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "奥迪A6L 12万公里大保养登记",
			Result:         "创建成功",
			RiskChange:     "none->low",
			EvidenceCheck:  "submitted=false",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 96),
		},
		{
			OrderID:        6,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "大保养工单提交",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "材料齐全",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 95),
		},
		{
			OrderID:        6,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "supervisor_review_approve",
			FromStatus:     models.StatusSubmitted,
			ToStatus:       models.StatusSupervisorApproved,
			Opinion:        "常规大保养项目，派周师傅执行，预计工时4小时。注意检查刹车片磨损情况，可能需要额外更换。",
			Result:         "主管审核通过",
			RiskChange:     "none",
			EvidenceCheck:  "通过",
			VersionChecked: 2,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 94),
		},
		{
			OrderID:        6,
			OperatorID:     registrar.ID,
			OperatorName:   "张登记",
			OperatorRole:   "registrar",
			Action:         "risk_change",
			FromStatus:     models.StatusSupervisorApproved,
			ToStatus:       models.StatusSupervisorApproved,
			Opinion:        "技师检查发现前刹车片磨损接近极限，需要额外更换，成本略有上升但不影响风险等级，维持低风险",
			Result:         "成功",
			RiskChange:     "none:low->low",
			EvidenceCheck:  "刹车片检查照片已补充",
			VersionChecked: 3,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 50),
		},
		{
			OrderID:        6,
			OperatorID:     reviewer.ID,
			OperatorName:   reviewer.RealName,
			OperatorRole:   reviewer.Role,
			Action:         "reviewer_review_approve",
			FromStatus:     models.StatusSupervisorApproved,
			ToStatus:       models.StatusArchived,
			Opinion:        "全部保养+维修项目已完成：变速箱油/刹车油/冷却液/火花塞/前后刹车片/刹车盘光碟。客户现场验车确认，刹车制动力达标，试驾无异常。已交车并完成3天后回访，客户表示非常满意。最终结算金额7250元（含刹车片额外更换费用450元）。",
			Result:         "复核通过-归档",
			RiskChange:     "none",
			EvidenceCheck:  "交车证据齐全：维修前后对比照、客户签字确认单、回访录音摘要、发票存根",
			VersionChecked: 4,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 2),
		},
		{
			OrderID:        7,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "宝马X5变速箱严重顿挫报修",
			Result:         "创建成功",
			RiskChange:     "none->medium",
			EvidenceCheck:  "submitted=false",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 240),
		},
		{
			OrderID:        7,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "提交变速箱故障工单",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "材料齐全",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 239),
		},
		{
			OrderID:        7,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "supervisor_review_approve",
			FromStatus:     models.StatusSubmitted,
			ToStatus:       models.StatusSupervisorApproved,
			Opinion:        "诊断判断为变速箱阀体故障，需更换阀体总成。配件需从德国原厂订货，预计等待时间较长。派吴师傅负责拆解和装配。",
			Result:         "主管审核通过",
			RiskChange:     "upgrade:medium->high",
			EvidenceCheck:  "故障码报告已确认",
			VersionChecked: 2,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 230),
		},
		{
			OrderID:        7,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "risk_change",
			FromStatus:     models.StatusSupervisorApproved,
			ToStatus:       models.StatusOverdue,
			Opinion:        "德国供应商通知：阀体因海关查验延误，预计到货时间再推迟10天。原定办理时限已过期5天，客户多次来电催促。标记逾期状态，升级为高风险，已向经理汇报并联系客户协商补偿方案（提供代步车+免费保养一次）。",
			Result:         "状态变更-逾期",
			RiskChange:     "upgrade:medium->high",
			EvidenceCheck:  "供应商邮件截图、海关查验通知已存档",
			VersionChecked: 3,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 12),
		},
		{
			OrderID:        8,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "create",
			FromStatus:     "",
			ToStatus:       models.StatusDraft,
			Opinion:        "特斯拉Model Y剐蹭事故维修",
			Result:         "创建成功",
			RiskChange:     "none->medium",
			EvidenceCheck:  "submitted=false",
			VersionChecked: 0,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 72),
		},
		{
			OrderID:        8,
			OperatorID:     registrar.ID,
			OperatorName:   registrar.RealName,
			OperatorRole:   registrar.Role,
			Action:         "submit",
			FromStatus:     models.StatusDraft,
			ToStatus:       models.StatusSubmitted,
			Opinion:        "提交特斯拉事故维修工单",
			Result:         "成功",
			RiskChange:     "none",
			EvidenceCheck:  "材料齐全",
			VersionChecked: 1,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 71),
		},
		{
			OrderID:        8,
			OperatorID:     supervisor.ID,
			OperatorName:   supervisor.RealName,
			OperatorRole:   supervisor.Role,
			Action:         "supervisor_review_approve",
			FromStatus:     models.StatusSubmitted,
			ToStatus:       models.StatusSupervisorApproved,
			Opinion:        "钣金喷漆工艺难度常规，注意Autopilot雷达移位必须使用专用校准设备恢复。派郑师傅处理。",
			Result:         "主管审核通过",
			RiskChange:     "none",
			EvidenceCheck:  "通过",
			VersionChecked: 2,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 70),
		},
		{
			OrderID:        8,
			OperatorID:     reviewer.ID,
			OperatorName:   reviewer.RealName,
			OperatorRole:   reviewer.Role,
			Action:         "reviewer_review_reject",
			FromStatus:     models.StatusSupervisorApproved,
			ToStatus:       models.StatusReviewerRejected,
			Opinion:        "质检发现问题：钣金喷漆工艺合格，但Autopilot校准报告数据异常——前向雷达横向偏移2.3mm（标准应≤0.5mm），直接影响FCW和AEB功能安全性。必须返工重新校准雷达支架，并使用特斯拉原厂校准工具完成重新标定，出具合格报告后再提交复核。返工期间禁止交车！",
			Result:         "复核退回-要求重做校准",
			RiskChange:     "none",
			EvidenceCheck:  "Autopilot校准报告不合格（偏差超限），需重新检测",
			VersionChecked: 3,
			IpAddress:      "127.0.0.1",
			CreatedAt:      now.Add(-time.Hour * 6),
		},
	}

	for i, op := range seedOperations {
		if err := db.Create(op).Error; err != nil {
			return fmt.Errorf("创建操作记录 %d 失败: %w", i+1, err)
		}
	}

	log.Println("种子数据初始化完成！")
	log.Printf("用户ID映射: registrar=%d, supervisor=%d, reviewer=%d",
		registrar.ID, supervisor.ID, reviewer.ID)
	log.Println("请使用 X-User-Id header 进行用户切换")
	return nil
}

func generateOrderNo(prefix string, seq int) string {
	now := time.Now()
	return fmt.Sprintf("WO%s%02d%02d%s%04d",
		now.Format("2006"), now.Month(), now.Day(), prefix, seq)
}
