# Generated by Django 5.2.15 on 2026-06-09 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('batch_no', models.CharField(max_length=32, verbose_name='批次号')),
                ('patient_name', models.CharField(max_length=64, verbose_name='患者姓名')),
                ('patient_id_card', models.CharField(blank=True, max_length=32, verbose_name='身份证号')),
                ('lens_type', models.CharField(blank=True, max_length=64, verbose_name='镜片类型')),
                ('lens_power', models.CharField(blank=True, max_length=64, verbose_name='镜片度数')),
                ('frame_model', models.CharField(blank=True, max_length=64, verbose_name='镜架型号')),
                ('prescription_no', models.CharField(blank=True, max_length=64, verbose_name='处方单号')),
                ('has_prescription', models.BooleanField(default=False, verbose_name='是否有处方单')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='是否有医保材料')),
                ('has_id_copy', models.BooleanField(default=False, verbose_name='是否有身份证复印件')),
                ('has_receipt', models.BooleanField(default=False, verbose_name='是否有收费凭证')),
                ('status', models.CharField(choices=[('pending_registration', '待登记'), ('pending_review', '待审核'), ('pending_final', '待复核'), ('archived', '已归档'), ('returned', '已退回'), ('abnormal', '异常')], default='pending_registration', max_length=32, verbose_name='订单状态')),
                ('offline_status', models.CharField(choices=[('not_recorded', '线下未登记'), ('registered', '线下已登记'), ('reviewed', '线下已审核'), ('finalized', '线下已复核'), ('archived', '线下已归档')], default='not_recorded', max_length=32, verbose_name='线下台账状态')),
                ('registered_by', models.CharField(blank=True, max_length=64, verbose_name='登记人')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='登记时间')),
                ('reviewed_by', models.CharField(blank=True, max_length=64, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('finalized_by', models.CharField(blank=True, max_length=64, verbose_name='复核人')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('return_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('return_by', models.CharField(blank=True, max_length=64, verbose_name='退回人')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='退回时间')),
                ('audit_remark', models.TextField(blank=True, verbose_name='审计备注')),
                ('result_remark', models.TextField(blank=True, verbose_name='结果说明')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否超时')),
                ('anomaly_types', models.JSONField(blank=True, default=list, verbose_name='异常类型列表')),
                ('anomaly_remark', models.TextField(blank=True, verbose_name='异常说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配镜订单',
                'verbose_name_plural': '配镜订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('role', models.CharField(choices=[('registrar', '配镜登记员'), ('supervisor', '配镜审核主管'), ('reviewer', '眼科诊所复核负责人')], max_length=32, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64, verbose_name='操作类型')),
                ('actor', models.CharField(max_length=64, verbose_name='操作人')),
                ('actor_role', models.CharField(choices=[('registrar', '配镜登记员'), ('supervisor', '配镜审核主管'), ('reviewer', '眼科诊所复核负责人')], max_length=32, verbose_name='操作人角色')),
                ('status_before', models.CharField(blank=True, max_length=32, verbose_name='操作前状态')),
                ('status_after', models.CharField(blank=True, max_length=32, verbose_name='操作后状态')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('is_failure', models.BooleanField(default=False, verbose_name='是否失败操作')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='glasses.glassesorder', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=64, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_url', models.CharField(blank=True, max_length=512, verbose_name='文件地址')),
                ('uploaded_by', models.CharField(max_length=64, verbose_name='上传人')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='glasses.glassesorder', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单附件',
                'verbose_name_plural': '订单附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
